### ISSUE TITLE
Potential small error in x40 schematic 

### ISSUE THREAD

**Issue by ivo1981** [openhaptics/openhaptics-hardware#4]
I think there's a +5v missing (com pin 10) on the most right uln2803
(The one connected directly to the esp

**Comment by leon0399** [comment]
Thank you! Yes, I've re-checked, and there is indeed an issue: I've missed one vibro motor (You can count only 7 motors attached to uln2803)
![image](https://user-images.githubusercontent.com/1759654/202858571-b98e9387-5afd-401b-b58c-30e2535ad7af.png)

**Comment by ivo1981** [comment]
![Screenshot_2022-11-19-16-35-55-959-edit_com brave browser](https://user-images.githubusercontent.com/7091645/202858781-d9c3110d-0bbd-4315-8f56-63176a681086.jpg)
Here also

**Comment by leon0399** [comment]
Ah, ok! Thank you!

**Comment by ivo1981** [comment]
You're welcome! I will be building a tactile later this week to try stuff out and then a x40. Thanks for the great work so far!

**Comment by leon0399** [comment]
> You're welcome! I will be building a tactile later this week to try stuff out and then a x40. Thanks for the great work so far!

Good luck! And consider sharing your results with us in discord 😉

**Comment by ivo1981** [comment]
Ah sure! I'll join now!
